name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: chmod +x setup.sh && ./setup.sh
    - name: Build
      run: make

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: pwd && chmod +x setup.sh && ./setup.sh
    - name: Run tests
      run: pwd && make test
