name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: chmod +x setup.sh && ./setup.sh
    - name: build
      run: make

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: chmod +x setup.sh && ./setup.sh
    - name: run tests
      run: make test
